/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_test;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class testingJUnit {

    @BeforeAll
    public static void testBeforeAll(){
        System.out.println("Before all");
    }

    @AfterAll
    public static void testAfterAll(){
        System.out.println("after all");
    }

    @BeforeEach
    public void BeforeEach(){
        System.out.println("before each");
    }

    @AfterEach
    public void AfterEach(){
        System.out.println("after each");
    }
    
    @Test
    public void testPenjumlahan(){
        System.out.println("test sukses");
        Assertions.assertEquals(4, 2+2);
    }

    @Test
    public void testPrint(){
        System.out.println("cuma print ini aja");
    }
}
